/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_CONSTANTS_H
#define test_CONSTANTS_H

#include "test_types.h"

namespace tutorial {

class testConstants {
 public:
  testConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const testConstants g_test_constants;

} // namespace

#endif
